version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
permissions:
  - object: /var/www/html
    pattern: "**"
    owner: root
    group: root
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/docker-login.sh
      timeout: 400
      runas: root
  AfterInstall:
    - location: scripts/docker-image.sh
      timeout: 400
      runas: root